### ISSUE TITLE
Accessing ObjectProperties `parent` raises AttributeError

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/python-cybox#254]
The `object_properties` module does not import `cybox.core`. 

```
>>> from cybox.objects.address_object import Address
>>> addr = Address()
>>> addr.parent.id_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bworrell/projects/python-cybox/cybox/common/object_properties.py", line 90, in parent
    self._parent = cybox.core.Object(self)
AttributeError: 'module' object has no attribute 'core'
>>> cybox.__version__
'2.1.0.12.dev0'
```

**Comment by gtback** [comment]
@bworrell did all the work for this, despite it being my commit that closed it.
